apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: ehsanwanclouds/hello-gitops
  newTag: f42fa979af0d033b40ca40edc9f043ad88166777
